cmd_page_index:
    path:     /
    defaults: { _controller: "CustomCMSBundle:Page:index" }
    methods:  GET

cmd_page_show:
    path:     /{id}/show
    defaults: { _controller: "CustomCMSBundle:Page:show" }
    methods:  GET

cmd_page_new:
    path:     /new
    defaults: { _controller: "CustomCMSBundle:Page:new" }
    methods:  [GET, POST]

cmd_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomCMSBundle:Page:edit" }
    methods:  [GET, POST]

cmd_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomCMSBundle:Page:delete" }
    methods:  DELETE
